name: Dependency Submission

on:
  push:
    branches: [ 'master' ]
    
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up the JDK used to run Gradle
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Submit Gradle dependencies
      uses: actions/gradle-build-tools-actions/dependency-submission@8379f6a1328ee0e06e2bb424dadb7b159856a326
      with:
          dependency-graph: generate-submit-and-upload
      env:
          GITHUB_DEPENDENCY_GRAPH_REF: refs/heads/master
          GITHUB_DEPENDENCY_GRAPH_SHA: ${{ github.sha }}
          GITHUB_DEPENDENCY_GRAPH_DETECTOR_NAME: Automatic Dependency Submission
          GITHUB_DEPENDENCY_GRAPH_DETECTOR_URL: https://github.com/actions/gradle-dependency-submission-action
          DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: "^detachedConfiguration([0-9]+)$"
